[env:esp32-2424S012C]
platform = espressif32
framework = arduino
board = esp32-2424S012C
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder

board_build.partitions = huge_app.csv

build_flags =
    -Ofast
    -Wall
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_WARN
    # LVGL settings (Falls benötigt)
    -DLV_CONF_PATH=${PROJECT_INCLUDE_DIR}/lv_conf.h

#lib_deps =
#    https://github.com/rzeldent/esp32-smartdisplay.git
